/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceSetEntity } from './PerformanceSetEntity';
import {
    PerformanceSetEntityFromJSON,
    PerformanceSetEntityFromJSONTyped,
    PerformanceSetEntityToJSON,
    PerformanceSetEntityToJSONTyped,
} from './PerformanceSetEntity';
import type { ImageEntity } from './ImageEntity';
import {
    ImageEntityFromJSON,
    ImageEntityFromJSONTyped,
    ImageEntityToJSON,
    ImageEntityToJSONTyped,
} from './ImageEntity';
import type { VenueEntity } from './VenueEntity';
import {
    VenueEntityFromJSON,
    VenueEntityFromJSONTyped,
    VenueEntityToJSON,
    VenueEntityToJSONTyped,
} from './VenueEntity';

/**
 * Make all properties in T optional
 * @export
 * @interface PartialEventCreateParams
 */
export interface PartialEventCreateParams {
    /**
     * 
     * @type {string}
     * @memberof PartialEventCreateParams
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof PartialEventCreateParams
     */
    eventStart?: Date;
    /**
     * 
     * @type {string}
     * @memberof PartialEventCreateParams
     */
    eventDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialEventCreateParams
     */
    eventGenre?: string;
    /**
     * 
     * @type {Array<ImageEntity>}
     * @memberof PartialEventCreateParams
     */
    eventImages?: Array<ImageEntity>;
    /**
     * 
     * @type {VenueEntity}
     * @memberof PartialEventCreateParams
     */
    eventLocation?: VenueEntity;
    /**
     * 
     * @type {Array<PerformanceSetEntity>}
     * @memberof PartialEventCreateParams
     */
    performanceSets?: Array<PerformanceSetEntity>;
}

/**
 * Check if a given object implements the PartialEventCreateParams interface.
 */
export function instanceOfPartialEventCreateParams(value: object): value is PartialEventCreateParams {
    return true;
}

export function PartialEventCreateParamsFromJSON(json: any): PartialEventCreateParams {
    return PartialEventCreateParamsFromJSONTyped(json, false);
}

export function PartialEventCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialEventCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'eventStart': json['eventStart'] == null ? undefined : (new Date(json['eventStart'])),
        'eventDescription': json['eventDescription'] == null ? undefined : json['eventDescription'],
        'eventGenre': json['eventGenre'] == null ? undefined : json['eventGenre'],
        'eventImages': json['eventImages'] == null ? undefined : ((json['eventImages'] as Array<any>).map(ImageEntityFromJSON)),
        'eventLocation': json['eventLocation'] == null ? undefined : VenueEntityFromJSON(json['eventLocation']),
        'performanceSets': json['performanceSets'] == null ? undefined : ((json['performanceSets'] as Array<any>).map(PerformanceSetEntityFromJSON)),
    };
}

export function PartialEventCreateParamsToJSON(json: any): PartialEventCreateParams {
    return PartialEventCreateParamsToJSONTyped(json, false);
}

export function PartialEventCreateParamsToJSONTyped(value?: PartialEventCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'eventStart': value['eventStart'] == null ? undefined : ((value['eventStart']).toISOString()),
        'eventDescription': value['eventDescription'],
        'eventGenre': value['eventGenre'],
        'eventImages': value['eventImages'] == null ? undefined : ((value['eventImages'] as Array<any>).map(ImageEntityToJSON)),
        'eventLocation': VenueEntityToJSON(value['eventLocation']),
        'performanceSets': value['performanceSets'] == null ? undefined : ((value['performanceSets'] as Array<any>).map(PerformanceSetEntityToJSON)),
    };
}

