/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageEntity } from './ImageEntity';
import {
    ImageEntityFromJSON,
    ImageEntityFromJSONTyped,
    ImageEntityToJSON,
    ImageEntityToJSONTyped,
} from './ImageEntity';

/**
 * Make all properties in T optional
 * @export
 * @interface PartialArtistCreateParams
 */
export interface PartialArtistCreateParams {
    /**
     * 
     * @type {ImageEntity}
     * @memberof PartialArtistCreateParams
     */
    imageUrl?: ImageEntity;
    /**
     * 
     * @type {string}
     * @memberof PartialArtistCreateParams
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialArtistCreateParams
     */
    genre?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialArtistCreateParams
     */
    bio?: string;
}

/**
 * Check if a given object implements the PartialArtistCreateParams interface.
 */
export function instanceOfPartialArtistCreateParams(value: object): value is PartialArtistCreateParams {
    return true;
}

export function PartialArtistCreateParamsFromJSON(json: any): PartialArtistCreateParams {
    return PartialArtistCreateParamsFromJSONTyped(json, false);
}

export function PartialArtistCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialArtistCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'] == null ? undefined : ImageEntityFromJSON(json['imageUrl']),
        'name': json['name'] == null ? undefined : json['name'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'bio': json['bio'] == null ? undefined : json['bio'],
    };
}

export function PartialArtistCreateParamsToJSON(json: any): PartialArtistCreateParams {
    return PartialArtistCreateParamsToJSONTyped(json, false);
}

export function PartialArtistCreateParamsToJSONTyped(value?: PartialArtistCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrl': ImageEntityToJSON(value['imageUrl']),
        'name': value['name'],
        'genre': value['genre'],
        'bio': value['bio'],
    };
}

