/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Make all properties in T optional
 * @export
 * @interface PartialImageCreateParams
 */
export interface PartialImageCreateParams {
    /**
     * 
     * @type {string}
     * @memberof PartialImageCreateParams
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialImageCreateParams
     */
    sourceImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialImageCreateParams
     */
    imageUrlLow?: string;
    /**
     * 
     * @type {number}
     * @memberof PartialImageCreateParams
     */
    aspectRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof PartialImageCreateParams
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof PartialImageCreateParams
     */
    height?: number;
}

/**
 * Check if a given object implements the PartialImageCreateParams interface.
 */
export function instanceOfPartialImageCreateParams(value: object): value is PartialImageCreateParams {
    return true;
}

export function PartialImageCreateParamsFromJSON(json: any): PartialImageCreateParams {
    return PartialImageCreateParamsFromJSONTyped(json, false);
}

export function PartialImageCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialImageCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'sourceImageUrl': json['sourceImageUrl'] == null ? undefined : json['sourceImageUrl'],
        'imageUrlLow': json['imageUrlLow'] == null ? undefined : json['imageUrlLow'],
        'aspectRatio': json['aspectRatio'] == null ? undefined : json['aspectRatio'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function PartialImageCreateParamsToJSON(json: any): PartialImageCreateParams {
    return PartialImageCreateParamsToJSONTyped(json, false);
}

export function PartialImageCreateParamsToJSONTyped(value?: PartialImageCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrl': value['imageUrl'],
        'sourceImageUrl': value['sourceImageUrl'],
        'imageUrlLow': value['imageUrlLow'],
        'aspectRatio': value['aspectRatio'],
        'width': value['width'],
        'height': value['height'],
    };
}

