/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageEntity } from './ImageEntity';
import {
    ImageEntityFromJSON,
    ImageEntityFromJSONTyped,
    ImageEntityToJSON,
    ImageEntityToJSONTyped,
} from './ImageEntity';

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
 */
export interface PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt {
    /**
     * 
     * @type {ImageEntity}
     * @memberof PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
     */
    imageUrl?: ImageEntity;
    /**
     * 
     * @type {string}
     * @memberof PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
     */
    genre: string;
    /**
     * 
     * @type {string}
     * @memberof PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt
     */
    bio?: string;
}

/**
 * Check if a given object implements the PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt interface.
 */
export function instanceOfPickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt(value: object): value is PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    return true;
}

export function PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtFromJSON(json: any): PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt {
    return PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtFromJSONTyped(json, false);
}

export function PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'] == null ? undefined : ImageEntityFromJSON(json['imageUrl']),
        'id': json['id'],
        'name': json['name'],
        'genre': json['genre'],
        'bio': json['bio'] == null ? undefined : json['bio'],
    };
}

export function PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtToJSON(json: any): PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt {
    return PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtToJSONTyped(json, false);
}

export function PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAtToJSONTyped(value?: PickClassPropertiesArtistEntityExcludeKeyofClassPropertiesArtistEntityCreatedAtOrUpdatedAtOrDeletedAt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrl': ImageEntityToJSON(value['imageUrl']),
        'id': value['id'],
        'name': value['name'],
        'genre': value['genre'],
        'bio': value['bio'],
    };
}

