/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceSetEntity } from './PerformanceSetEntity';
import {
    PerformanceSetEntityFromJSON,
    PerformanceSetEntityFromJSONTyped,
    PerformanceSetEntityToJSON,
    PerformanceSetEntityToJSONTyped,
} from './PerformanceSetEntity';
import type { ImageEntity } from './ImageEntity';
import {
    ImageEntityFromJSON,
    ImageEntityFromJSONTyped,
    ImageEntityToJSON,
    ImageEntityToJSONTyped,
} from './ImageEntity';
import type { VenueEntity } from './VenueEntity';
import {
    VenueEntityFromJSON,
    VenueEntityFromJSONTyped,
    VenueEntityToJSON,
    VenueEntityToJSONTyped,
} from './VenueEntity';

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickEventExcludeKeyofEventId
 */
export interface PickEventExcludeKeyofEventId {
    /**
     * 
     * @type {string}
     * @memberof PickEventExcludeKeyofEventId
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PickEventExcludeKeyofEventId
     */
    eventStart: Date;
    /**
     * 
     * @type {string}
     * @memberof PickEventExcludeKeyofEventId
     */
    eventDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PickEventExcludeKeyofEventId
     */
    eventGenre?: string;
    /**
     * 
     * @type {Array<ImageEntity>}
     * @memberof PickEventExcludeKeyofEventId
     */
    eventImages?: Array<ImageEntity>;
    /**
     * 
     * @type {VenueEntity}
     * @memberof PickEventExcludeKeyofEventId
     */
    eventLocation?: VenueEntity;
    /**
     * 
     * @type {Array<PerformanceSetEntity>}
     * @memberof PickEventExcludeKeyofEventId
     */
    performanceSets?: Array<PerformanceSetEntity>;
}

/**
 * Check if a given object implements the PickEventExcludeKeyofEventId interface.
 */
export function instanceOfPickEventExcludeKeyofEventId(value: object): value is PickEventExcludeKeyofEventId {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('eventStart' in value) || value['eventStart'] === undefined) return false;
    return true;
}

export function PickEventExcludeKeyofEventIdFromJSON(json: any): PickEventExcludeKeyofEventId {
    return PickEventExcludeKeyofEventIdFromJSONTyped(json, false);
}

export function PickEventExcludeKeyofEventIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickEventExcludeKeyofEventId {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'eventStart': (new Date(json['eventStart'])),
        'eventDescription': json['eventDescription'] == null ? undefined : json['eventDescription'],
        'eventGenre': json['eventGenre'] == null ? undefined : json['eventGenre'],
        'eventImages': json['eventImages'] == null ? undefined : ((json['eventImages'] as Array<any>).map(ImageEntityFromJSON)),
        'eventLocation': json['eventLocation'] == null ? undefined : VenueEntityFromJSON(json['eventLocation']),
        'performanceSets': json['performanceSets'] == null ? undefined : ((json['performanceSets'] as Array<any>).map(PerformanceSetEntityFromJSON)),
    };
}

export function PickEventExcludeKeyofEventIdToJSON(json: any): PickEventExcludeKeyofEventId {
    return PickEventExcludeKeyofEventIdToJSONTyped(json, false);
}

export function PickEventExcludeKeyofEventIdToJSONTyped(value?: PickEventExcludeKeyofEventId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'eventStart': ((value['eventStart']).toISOString()),
        'eventDescription': value['eventDescription'],
        'eventGenre': value['eventGenre'],
        'eventImages': value['eventImages'] == null ? undefined : ((value['eventImages'] as Array<any>).map(ImageEntityToJSON)),
        'eventLocation': VenueEntityToJSON(value['eventLocation']),
        'performanceSets': value['performanceSets'] == null ? undefined : ((value['performanceSets'] as Array<any>).map(PerformanceSetEntityToJSON)),
    };
}

