/* tslint:disable */
/* eslint-disable */
/**
 * lineup-backstage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceSetEntity } from './PerformanceSetEntity';
import {
    PerformanceSetEntityFromJSON,
    PerformanceSetEntityFromJSONTyped,
    PerformanceSetEntityToJSON,
    PerformanceSetEntityToJSONTyped,
} from './PerformanceSetEntity';
import type { VenueEntity } from './VenueEntity';
import {
    VenueEntityFromJSON,
    VenueEntityFromJSONTyped,
    VenueEntityToJSON,
    VenueEntityToJSONTyped,
} from './VenueEntity';

/**
 * 
 * @export
 * @interface StageEntity
 */
export interface StageEntity {
    /**
     * Stringified UUIDv4.
     * See [RFC 4112](https://tools.ietf.org/html/rfc4122)
     * @type {string}
     * @memberof StageEntity
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof StageEntity
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StageEntity
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StageEntity
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof StageEntity
     */
    name: string;
    /**
     * 
     * @type {VenueEntity}
     * @memberof StageEntity
     */
    venue: VenueEntity;
    /**
     * 
     * @type {Array<PerformanceSetEntity>}
     * @memberof StageEntity
     */
    set: Array<PerformanceSetEntity>;
}

/**
 * Check if a given object implements the StageEntity interface.
 */
export function instanceOfStageEntity(value: object): value is StageEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    if (!('set' in value) || value['set'] === undefined) return false;
    return true;
}

export function StageEntityFromJSON(json: any): StageEntity {
    return StageEntityFromJSONTyped(json, false);
}

export function StageEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'name': json['name'],
        'venue': VenueEntityFromJSON(json['venue']),
        'set': ((json['set'] as Array<any>).map(PerformanceSetEntityFromJSON)),
    };
}

export function StageEntityToJSON(json: any): StageEntity {
    return StageEntityToJSONTyped(json, false);
}

export function StageEntityToJSONTyped(value?: StageEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'name': value['name'],
        'venue': VenueEntityToJSON(value['venue']),
        'set': ((value['set'] as Array<any>).map(PerformanceSetEntityToJSON)),
    };
}

